### ISSUE TITLE
Runtime error in Windows

### ISSUE THREAD

**Issue by SergeyMi37** [nickmitchko/zbash#1]
And what is strange, the shell above the shell, works worse than the main shell.

ZBASH>zpm "list"
zbash 0.0.3
zpipe 1.1.0

ZBASH>zpipe "ver"
 
Microsoft Windows [Version 10.0.19045.2604]
 
ZBASH>zbash "ver"
??? ? 㤠????㪠????
 
ZBASH>zbash "dir d:\files"
??? ? 㤠????㪠????
 
ZBASH>zpipe "dir d:\files"
 ? ? ??? D ??? notebook
 
 ?ন? ? d:\files
 
28.04.2021  20:03    <DIR>          .
28.04.2021  20:03    <DIR>          ..
03.03.2021  09:28    <DIR>          audio
19.01.2020  20:16    <DIR>          bookmarks
07.10.2021  21:11    <DIR>          books
03.03.2021  09:28    <DIR>          camera
               0 䠩?              0 ??
               6 ?  115?293?282?304 ??᢮?

**Comment by nickmitchko** [comment]
zbash can't execute properly because bash isn't a default windows program.

I thought about expecting wsl installed on the system and for windows programs using wsl to execute bash commands in a one liner, but I decided against it because windows server typically does not have wsl installed.

If you have an idea how you'd like this to work on Windows systems, I'd love any suggestions!

```ps1
wsl -- /bin/bash -c "command" 2>&1
```

**Comment by nickmitchko** [comment]
Conversely, I could be "evil" and ship a bash binary as part of the install, but generally that's bad practice

**Comment by SergeyMi37** [comment]
I'm quite satisfied with how the zpipe shell works. Why doesn't the zbash shell work the same way, even though it's programmatically based on zpipe ?

**Comment by nickmitchko** [comment]
Because it doesn't just open a process like zpipe does, it opens the exact process `/bin/bash -c` with your command piped into it. Therefore, if you don't have /bin/bash on your machine, it won't work. I decided against supporting windows for this reason.

**Comment by SergeyMi37** [comment]
Then everything is clear, but then you need to inform in some way that this does not work on windows.

**Comment by nickmitchko** [comment]
I reopened this, there is a way to get this working on windows but I'll have to test a bit.

**Comment by nickmitchko** [comment]
@SergeyMi37 Can you try this changes in the branch `dev-os-support`?

```objectscript
zpipe "git clone -b dev-os-support --single-branch https://github.com/nickmitchko/zbash.git"
zpm "load ./zbash/"
```

**Comment by nickmitchko** [comment]
I just added a new release 0.0.5, supports windows using wsl or powershell as a fallback

**Comment by SergeyMi37** [comment]
It works great, thanks
